name: mi primer pipeline

on:
#ejcutar cada que se realic push
  push: 
    branches:
    - main
    - release/*
  pull_request:
    types: [opend,synchroniza, reopened, review_requested]
    branches:
    - main

    # ejecutar de manera programada
  schedule:
    - cron: "0 2 * * 1-5"
  #permitir ejecutar manualmente
  workflow_dispatch:

jobs:
  correr-tests:
    runs-on: ubuntu-latest

    steps:
      - name: realizamos checkout a la rama
        uses: actions/checkout@v2
      - name: usamos node.js 20.x
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          cache: 'npm'


      - name: iniciamos dependencias y realizamos el build
        run: |
          npm install
          npm run buid --if-present
