name: mi primer pipeline

on:
#ejcutar cada que se realic push
  push: 
    branches:
    - main
    - release/*
  pull_request:
    types: [opend,synchroniza, reopened, review_requested]
    branches:
    - main

    # ejecutar de manera programada
  schedule:
    - cron: "0 2 * * 1-5"
  #permitir ejecutar manualmente
  workflow_dispatch:

jobs:
  correr-tests:
    runs-on: ubuntu-latest

    steps:
      - name: realizamos checkout a la rama
        uses: actions/checkout@v2
      - name: usamos node.js 20.x
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          cache: 'npm'


      - name: iniciamos dependencias y realizamos el build
        run: |
          npm install
          npm run buid --if-present


  #    - name: correr el linter
  #      run: npm run lint

      - name: corremos las pruebas unitarias y de inteegracion con su covertura
        run: npm run test:cov

      - name: corremos las pruebas end-to-end
        run: npm run test:e2e

      - name: actualizamos el artefacto con el reporte de covertura de los tsts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
          if-no-fies-found: error

  crear-artefacto:
    needs: correr-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Usamos Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Instalamos las dependencias
      run: npm ci
    
    - name: Realizamos el build de la aplicación
      run: npm run build
    
    - name: Actualizamos el artefacto
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: dist/
        retention-days: 7
        if-no-files-found: error
